let
    Source = Folder.Files("D:\Data Analytics Portfolio\Infrabel_Punctuality\01 - Raw data"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"DATDEP", type date}, {"TRAIN_NO", Int64.Type}, {"RELATION", type text}, {"TRAIN_SERV", type text}, {"PTCAR_NO", Int64.Type}, {"THOP1_COD", type text}, {"LINE_NO_DEP", type text}, {"REAL_TIME_ARR", type time}, {"REAL_TIME_DEP", type time}, {"PLANNED_TIME_ARR", type time}, {"PLANNED_TIME_DEP", type time}, {"DELAY_ARR", Int64.Type}, {"DELAY_DEP", Int64.Type}, {"CIRC_TYP", Int64.Type}, {"RELATION_DIRECTION", type text}, {"PTCAR_LG_NM_NL", type text}, {"LINE_NO_ARR", type text}, {"PLANNED_DATE_ARR", type date}, {"PLANNED_DATE_DEP", type date}, {"REAL_DATE_ARR", type date}, {"REAL_DATE_DEP", type date}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type"),
    #"Removed Columns" = Table.RemoveColumns(#"Removed Duplicates",{"TRAIN_SERV", "PTCAR_NO", "THOP1_COD", "CIRC_TYP"}),
    #"Split Column by Character Transition" = Table.SplitColumn(#"Removed Columns", "RELATION", Splitter.SplitTextByCharacterTransition((c) => not List.Contains({"0".."9"}, c), {"0".."9"}), {"RELATION.1", "RELATION.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Character Transition",{{"RELATION.1", type text}, {"RELATION.2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"RELATION.2"}),
    #"Trimmed Text" = Table.TransformColumns(#"Removed Columns1",{{"RELATION.1", Text.Trim, type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Trimmed Text", each ([RELATION.1] = "IC" or [RELATION.1] = "S" or [RELATION.1] = "L" or [RELATION.1] = "P")),
    #"Replaced Value2" = Table.ReplaceValue(#"Filtered Rows","","P",Replacer.ReplaceValue,{"RELATION_DIRECTION"}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Replaced Value2", "RELATION_DIRECTION", Splitter.SplitTextByEachDelimiter({":"}, QuoteStyle.Csv, false), {"RELATION_DIRECTION.1", "RELATION_DIRECTION.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"RELATION_DIRECTION.1", type text}, {"RELATION_DIRECTION.2", type text}}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Changed Type2", "RELATION_DIRECTION.2", Splitter.SplitTextByEachDelimiter({"->"}, QuoteStyle.Csv, false), {"RELATION_DIRECTION.2.1", "RELATION_DIRECTION.2.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"RELATION_DIRECTION.2.1", type text}, {"RELATION_DIRECTION.2.2", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type3",{{"DATDEP", "Service Date"}, {"TRAIN_NO", "Train No."}, {"RELATION.1", "Train Type"}, {"LINE_NO_DEP", "Departure Line"}, {"REAL_TIME_ARR", "Actual Arrival Time"}, {"REAL_TIME_DEP", "Actual Departure Time"}, {"PLANNED_TIME_ARR", "Planned Arrival Time"}, {"PLANNED_TIME_DEP", "Planned Departure Time"}, {"DELAY_ARR", "Delay at Arrival"}, {"DELAY_DEP", "Delay at Departure"}, {"RELATION_DIRECTION.1", "Train Relation"}, {"RELATION_DIRECTION.2.1", "Starting Station"}, {"RELATION_DIRECTION.2.2", "Ending Station"}, {"PTCAR_LG_NM_NL", "Stopping Place"}, {"LINE_NO_ARR", "Arrival Line"}, {"PLANNED_DATE_ARR", "Planned Arrival Date"}, {"PLANNED_DATE_DEP", "Planned Departure Date"}, {"REAL_DATE_ARR", "Actual Arrival Date"}, {"REAL_DATE_DEP", "Actual Departure Date"}}),
    #"Inserted Merged Date and Time" = Table.AddColumn(#"Renamed Columns", "Merged", each [Planned Departure Time] & [Planned Departure Date], type datetime),
    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Merged Date and Time",{{"Merged", "Planned Departure DateTime"}}),
    #"Inserted Merged Date and Time1" = Table.AddColumn(#"Renamed Columns1", "Merged", each [Actual Departure Time] & [Actual Departure Date], type datetime),
    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Merged Date and Time1",{{"Merged", "Actual Departure DateTime"}}),
    #"Inserted Merged Date and Time2" = Table.AddColumn(#"Renamed Columns2", "Merged", each [Planned Arrival Time] & [Planned Arrival Date], type datetime),
    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Merged Date and Time2",{{"Merged", "Planned Arrival DateTime"}}),
    #"Inserted Merged Date and Time3" = Table.AddColumn(#"Renamed Columns3", "Merged", each [Actual Arrival Time] & [Actual Arrival Date], type datetime),
    #"Renamed Columns4" = Table.RenameColumns(#"Inserted Merged Date and Time3",{{"Merged", "Actual Arrival DateTime"}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns4",{"Actual Arrival Time", "Actual Departure Time", "Planned Arrival Time", "Planned Departure Time", "Planned Arrival Date", "Planned Departure Date", "Actual Arrival Date", "Actual Departure Date"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns2", "HasArrival", each [Planned Arrival DateTime] <> null),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom",{{"HasArrival", type logical}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type4", "HasDeparture", each [Actual Departure DateTime] <> null),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom1",{{"HasDeparture", type logical}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type5","",null,Replacer.ReplaceValue,{"Arrival Line"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","",null,Replacer.ReplaceValue,{"Departure Line"}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Replaced Value1",{{"Train No.", type text}}),
    #"Filtered Rows1" = Table.SelectRows(#"Changed Type6", each not Text.Contains([Stopping Place], "-BUNDEL") and not Text.Contains([Stopping Place], "-FAISCEAU") and not Text.Contains([Stopping Place], "-GOEDEREN") and not Text.Contains([Stopping Place], "-AFWISSELING") and not Text.Contains([Stopping Place], "-FORMATION") and not Text.Contains([Stopping Place], "-AFLOS") and not Text.Contains([Stopping Place], "-PERRON") and not Text.Contains([Stopping Place], "-CARWASH") and not Text.Contains([Stopping Place], "-SAS") and not Text.Contains([Stopping Place], "-GARAGE") and not Text.Contains([Stopping Place], "-WIJKSPOOR") and not Text.Contains([Stopping Place], "-WIJKSPOREN") and not Text.Contains([Stopping Place], "-KRUISSPOOR") and not Text.Contains([Stopping Place], "-KRUISSPOREN") and not Text.Contains([Stopping Place], "-MARCHANDISE") and not Text.Contains([Stopping Place], "-MARCHANDISES") and not Text.Contains([Stopping Place], "-GARE INDUSTRIELLE") and not Text.Contains([Stopping Place], "-RELAIS") and not Text.Contains([Stopping Place], "-T.W.") and not Text.Contains([Stopping Place], "-WIJKBUNDEL"))
in
    #"Filtered Rows1"